### ISSUE TITLE
Getting started issues

### ISSUE THREAD

**Issue by mslourens** [openimis/rest_api_c-sharp#12]
I came across your system, openIMIS, when researching for possible solutions for clinics in Africa who don't have a HMS or IMIS. I tried to run it on my machine, but got stuck. I hope you can help me out. I did the following:
- Install MSSQL Server Express 2017
- Clone the repositories database_ms_sqlserver, rest_api_c-sharp and web_app_vb
- Restore the database openIMIS_ONLINE_v1.2.0.bak
- Run the stored procedure SETUP-IMIS (which doesn't do much, it looks like a template)
- Debug rest_api_c-sharp in VS Studio 2017 Community Edition
- Run Postman and test the url http://localhost:35788/api/login with body {
    "Username": "Admin",
    "Password": "Admin"
}

When I try to login, I get an unauthorized error (401), and when I set a breakpoint in the UsersControllerV1.cs it cannot find the user. I tried to run the update script, which creates a second admin user. It is able to find that user, but the privatekey field is empty and needs to be filled with something, because this line is depending on that value: var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(user.PrivateKey));

Any ideas what I am missing or doing wrong?

**Comment by dragos-dobre** [comment]
This component of openIMIS is a work in progress and has not been released yet. Its functionality is very limited. 
If you want to test openIMIS, please try our demo instance on https://demo.openimis.org/ or you can install it on your machine by following up the installation guide from https://openimis.readthedocs.io/en/latest/ .

**Comment by mslourens** [comment]
I followed that guide, but could not login after restoring the database backup. Should I not clone these repositories? Because the installation guide mentions this as well: 

> First, download the openIMIS database backup files and migration scripts from Github repository (the source code ZIP file)

**Comment by avanobberghen** [comment]
We just released a fix for the database. Could you please download this version?
Also, should you have further issues, please use the current issue tracking tool (JIRA), thanks. https://openimis.atlassian.net/servicedesk/customer/portal/1

**Comment by dragos-dobre** [comment]
We will close this issue as no communication happened for long time.
