### ISSUE TITLE
Enrollment vs Enrolment

### ISSUE THREAD

**Issue by ChristianDavis** [openimis/rest_api_c-sharp#139]
The American spelling (Enrollment) and the British spelling (Enrolment) seem to be used interchangeably throughout this repo. Is that by design?

**Comment by delcroip** [comment]
@dragos-dobre  please comment

**Comment by dragos-dobre** [comment]
The [Contribution guidelines](https://openimis.atlassian.net/wiki/spaces/OP/pages/1425473537/Contribution+guidelines#Variables) mention the variable naming using British spelling. The mentioned spelling will be fixed based on this constraint.
